package:
  name: tinyarray
  version: "1.1.0"

source:
  git_url: https://gitlab.kwant-project.org/kwant/tinyarray.git
  git_tag: v1.1.0 

requirements:
  build:
    - python
    - setuptools
    - nose
    - gcc

  run:
    - python
    - nose

about:
  home: https://gitlab.kwant-project.org/kwant/tinyarray
  license: BSD License
  summary: 'Arrays of numbers for Python, optimized for small sizes'

build:
  number: 4
